homepage:
    pattern:  /{page}
    defaults: { _controller: EtheriqLesson8Bundle:Main:showHomePage, page: 1 }
    requirements:
            page:  \d+

show_info:
    pattern: /show/{slug}
    defaults: { _controller: EtheriqLesson8Bundle:Main:showMoreInfo }

delete_item:
    pattern: /del/{slug}
    defaults: { _controller: EtheriqLesson8Bundle:Main:deleteItem }
